# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Shattered Stars"

# URL
baseurl:            "/shattered-stars"
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Synopsis"
    href:           "//baskervald.github.io/shattered-stars/synopsis"
  - name:           "Table of Contents"
    href:           "//baskervald.github.io/shattered-stars/toc"
  - name:           "About Me"
    href:           "//baskervald.github.io/shattered-stars/about-me"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
