# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Shattered Stars"

# URL
url:                "http://baskervald.github.io"
baseurl:            "/shattered-stars"
permalink:          /shattered-stars/:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//baskervald.github.io/shattered-stars/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
